// Generated by scripts/generate-county-centroids.mjs — do not edit by hand.
// Centroids computed from Kenya ADM1 boundaries (geoBoundaries open data).
// Keys are normalized county names (lowercase, alphanumeric only).

export interface CountyCentroid {
  name: string;
  lat: number;
  lng: number;
}

export const COUNTY_CENTROIDS: Record<string, CountyCentroid> = {
  "baringo": { name: "Baringo", lat: 0.6764, lng: 35.9403 },
  "bomet": { name: "Bomet", lat: -0.6915, lng: 35.2813 },
  "bungoma": { name: "Bungoma", lat: 0.7513, lng: 34.6392 },
  "busia": { name: "Busia", lat: 0.39, lng: 34.1938 },
  "elgeyomarakwet": { name: "Elgeyo-Marakwet", lat: 0.7995, lng: 35.5364 },
  "embu": { name: "Embu", lat: -0.6013, lng: 37.6252 },
  "garissa": { name: "Garissa", lat: -0.4883, lng: 40.1808 },
  "homabay": { name: "Homa Bay", lat: -0.541, lng: 34.3604 },
  "isiolo": { name: "Isiolo", lat: 1.0119, lng: 38.5391 },
  "kajiado": { name: "Kajiado", lat: -2.1206, lng: 36.9091 },
  "kakamega": { name: "Kakamega", lat: 0.4055, lng: 34.744 },
  "kericho": { name: "Kericho", lat: -0.2437, lng: 35.3366 },
  "kiambu": { name: "Kiambu", lat: -1.0667, lng: 36.8197 },
  "kilifi": { name: "Kilifi", lat: -3.1732, lng: 39.6831 },
  "kirinyaga": { name: "Kirinyaga", lat: -0.5223, lng: 37.3186 },
  "kisii": { name: "Kisii", lat: -0.7731, lng: 34.7761 },
  "kisumu": { name: "Kisumu", lat: -0.1684, lng: 34.8346 },
  "kitui": { name: "Kitui", lat: -1.4859, lng: 38.4058 },
  "kwale": { name: "Kwale", lat: -4.139, lng: 39.1515 },
  "laikipia": { name: "Laikipia", lat: 0.3239, lng: 36.7625 },
  "lamu": { name: "Lamu", lat: -2.0396, lng: 40.7662 },
  "machakos": { name: "Machakos", lat: -1.2898, lng: 37.4057 },
  "makueni": { name: "Makueni", lat: -2.1662, lng: 37.7997 },
  "mandera": { name: "Mandera", lat: 3.4384, lng: 40.7368 },
  "marsabit": { name: "Marsabit", lat: 2.9805, lng: 37.5679 },
  "meru": { name: "Meru", lat: 0.1717, lng: 37.7601 },
  "migori": { name: "Migori", lat: -0.9904, lng: 34.3638 },
  "mombasa": { name: "Mombasa", lat: -4.0177, lng: 39.6547 },
  "muranga": { name: "Murang'a", lat: -0.8089, lng: 37.0311 },
  "nairobi": { name: "Nairobi", lat: -1.2927, lng: 36.8644 },
  "nakuru": { name: "Nakuru", lat: -0.464, lng: 36.0763 },
  "nandi": { name: "Nandi", lat: 0.1854, lng: 35.1123 },
  "narok": { name: "Narok", lat: -1.2539, lng: 35.5753 },
  "nyamira": { name: "Nyamira", lat: -0.6424, lng: 34.9648 },
  "nyandarua": { name: "Nyandarua", lat: -0.3181, lng: 36.4779 },
  "nyeri": { name: "Nyeri", lat: -0.3431, lng: 36.9538 },
  "samburu": { name: "Samburu", lat: 1.3198, lng: 37.1168 },
  "siaya": { name: "Siaya", lat: -0.0584, lng: 34.2472 },
  "taitataveta": { name: "Taita Taveta", lat: -3.4325, lng: 38.4181 },
  "tanariver": { name: "Tana River", lat: -1.5572, lng: 39.4122 },
  "tharaka": { name: "Tharaka", lat: -0.199, lng: 37.8717 },
  "transnzoia": { name: "Trans Nzoia", lat: 1.0518, lng: 34.9571 },
  "turkana": { name: "Turkana", lat: 3.413, lng: 35.4349 },
  "uasingishu": { name: "Uasin Gishu", lat: 0.5321, lng: 35.3186 },
  "vihiga": { name: "Vihiga", lat: 0.0782, lng: 34.7219 },
  "wajir": { name: "Wajir", lat: 1.8098, lng: 40.0336 },
  "westpokot": { name: "West Pokot", lat: 1.7273, lng: 35.2431 },
};

const ALIASES: Record<string, string> = {
  "tharakanithi": "tharaka"
};

export function normalizeCountyName(name?: string | null): string {
  return (name || '').toLowerCase().replace(/[^a-z0-9]+/g, '');
}

export function getCountyCentroid(name?: string | null): CountyCentroid | null {
  const key = normalizeCountyName(name);
  return COUNTY_CENTROIDS[key] || COUNTY_CENTROIDS[ALIASES[key]] || null;
}
